# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - run: cat /home/runner/work/EntityFrameworkCore/EntityFrameworkCore/global.json
    - name: Restore Central Files
      run: dotnet restore *.restoreproj -t:RestoreCentralFiles
    - name: Restore dependencies
      run: dotnet restore *.slnproj
    - name: Restore Central Files
      run: dotnet build  --no-restore *.slnproj
    - name: Test
      run: dotnet test --no-build --verbosity normal
