# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
  setup-dotnet:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
  restore:
    runs-on: ubuntu-latest
    needs: setup-dotnet
    steps:
    - name: Restore dependencies
      run: dotnet restore
    - name: Restore Central Files
      run: dotnet build *.restoreproj -t:RestoreCentralFiles
  build:
    runs-on: ubuntu-latest
    needs: restore
    steps:
    - name: Build
      run: dotnet build --no-restore *.slnproj
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Test
      run: dotnet test --no-build --verbosity normal
